# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[("dev", "Development"), ("test", "Testing / QA"), ("prod", "Production")],
                        default="dev",
                        help_text="Type of Open edX environment in which this configuration will be used.",
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "stepwise_host",
                    models.URLField(
                        blank=True, help_text="the URL pointing to the Querium Stepwise Server.", max_length=255
                    ),
                ),
            ],
        ),
    ]
