# Generated by Django 2.2.25 on 2022-01-14 20:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("stepwise_plugin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locale",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "element_id",
                    models.CharField(help_text="An html element id. Example: stepwise-locale-contact", max_length=255),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es-419", "Español (Latinoamérica)"),
                            ("pt-pt", "Português (Portugal)"),
                        ],
                        help_text="A language code. Examples: en, en-US, es, es-419, es-MX",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL for for anchor tag for this language. Example: https://mx.stepwisemath.ai/contact/"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The text value of this html element. Example: Contacto", max_length=255
                    ),
                ),
            ],
            options={
                "unique_together": {("element_id", "lang")},
            },
        ),
    ]
