# Generated by Django 2.2.25 on 2022-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stepwise_plugin", "0003_auto_20220115_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingsites",
            name="province",
            field=models.CharField(
                blank=True,
                help_text="A sub-region for the language code. Example: for language code en-US valid possibles include TX, FL, CA, DC, KY, etc.",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketingsites",
            unique_together={("language", "province")},
        ),
    ]
